=== SaulGomez2003/lnd-ejercicos-y-tareas/ut02-ejercicios/ut02-ejercicios/02-Validación-de-documentos-XML-con-DTD/ejercicio05/factura.dtd
<!ELEMENT Factura (Fecha, Número, Fecha_de_vencimiento, Cliente, Empresa, Listado, Base_Disponible, IVA, IRPF, TOTAL, Comentarios, Pago_por_transferencia)>

<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Número (#PCDATA)>
<!ELEMENT Fecha_de_vencimiento (#PCDATA)>

<!ELEMENT Cliente (Nombre, Dirección, NIF, CP, Ciudad, Email)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Dirección (#PCDATA)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT CP (#PCDATA)>
<!ELEMENT Ciudad (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

<!ELEMENT Empresa (Dirección, CIF, CP, Ciudad, Email)>
<!ELEMENT CIF (#PCDATA)>


<!ELEMENT Listado (Producto+)>
<!ELEMENT Producto (Unidades, Precio_Unitario, Precio)>
<!ELEMENT Unidades (#PCDATA)>
<!ATTLIST Precio_Unitario moneda CDATA #REQUIRED>
<!ELEMENT Precio_Unitario (#PCDATA)>
<!ATTLIST Precio moneda CDATA #REQUIRED>
<!ELEMENT Precio (#PCDATA)>

<!ATTLIST Base_Disponible moneda CDATA #REQUIRED>
<!ELEMENT Base_Disponible (#PCDATA)>

<!ATTLIST IVA moneda CDATA #REQUIRED>
<!ELEMENT IVA (#PCDATA)>

<!ATTLIST IRPF moneda CDATA #REQUIRED>
<!ELEMENT IRPF (#PCDATA)>

<!ATTLIST TOTAL moneda CDATA #REQUIRED>
<!ELEMENT TOTAL (#PCDATA)>

<!ELEMENT Comentarios (#PCDATA)>
<!ELEMENT Pago_por_transferencia (#PCDATA)>

=== SaulGomez2003/lnd-ejercicos-y-tareas/ut02-ejercicios/ut02-ejercicios/01-Introducción-a-XML/ejercicio05/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Factura SYSTEM "factura.dtd">

<Factura>
    <Fecha>17/04/2024</Fecha>
    <Número>2024-0001</Número>
    <Fecha_de_vencimiento>17/05/2024</Fecha_de_vencimiento>
    
    <Cliente>
         <Nombre>Orlando Juan Lobán</Nombre>
         <Dirección>Avenida Rosario 2, 1 A</Dirección>
         <NIF>39000001A</NIF>
         <CP>08001</CP>
         <Ciudad>Barcelona</Ciudad>
         <Email>info@orlanjuan.es</Email>
    </Cliente>
    <Empresa>
         <Dirección>Calle San Juan de la Luz, s/n</Dirección>
         <CIF>B12345678</CIF>
         <CP>28001</CP>
         <Ciudad>Madrid</Ciudad>
         <Email>info@empresalogisitasl.com</Email>
    </Empresa>

    <Listado>
        <Producto>
             <Unidades>2</Unidades>
             <Precio_Unitario moneda="EUR">100.00</Precio_Unitario>
             <Precio moneda="EUR">200.00</Precio>
        </Producto>
        
        <Producto>
             <Unidades>4</Unidades>
             <Precio_Unitario moneda="EUR">150.00</Precio_Unitario>
             <Precio moneda="EUR">600.00</Precio>
        </Producto>
        
        <Producto>
             <Unidades>7</Unidades>
             <Precio_Unitario moneda="EUR">93.00</Precio_Unitario>
             <Precio moneda="EUR">651.00</Precio>
        </Producto>
    </Listado>

    <Base_Disponible moneda="EUR">1.451</Base_Disponible>
    <IVA moneda="EUR">304,71</IVA>
    <IRPF moneda="EUR">-217,65</IRPF>
    <TOTAL moneda="EUR">1.538,06</TOTAL>

    <Comentarios></Comentarios>
    <Pago_por_transferencia>ESXXXXXXXXXXXXXXXXX9</Pago_por_transferencia>
</Factura>
