=== SaulGomez2003/lnd-ejercicos-y-tareas/ut02-ejercicios/ut02-ejercicios/01-Introducción-a-XML/ejercicio04/maquinas-virtuales.dtd
<!ELEMENT Máquinas_Virtuales (ID+)>
<!ELEMENT ID (Nombre, CPU, RAM, Nom.Disco, Disco, Adaptador_de_red)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT CPU (#PCDATA)>
<!ELEMENT RAM (#PCDATA)>
<!ELEMENT Nom.Disco (#PCDATA)>
<!ELEMENT Disco (#PCDATA)>
<!ATTLIST Disco tamaño ID #REQUIRED>
<!ELEMENT Adaptador_de_red (#PCDATA)>

=== SaulGomez2003/lnd-ejercicos-y-tareas/ut02-ejercicios/ut02-ejercicios/01-Introducción-a-XML/ejercicio04/maquinas-virtuales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Máquinas_Virtuales SYSTEM "maquinas-virtuales.dtd">

<Máquinas_Virtuales>
    <ID>
        <Nombre>linuxmint21.3</Nombre>
        <CPU>2</CPU>
        <RAM tamaño="MB">4096</RAM>
        <Nom.Disco>/home/user/VirtualBox VMs/LinuxMint21.3/LinuxMint21.3.vdi</Nom.Disco>
        <Disco tamaño="GB">40</Disco> 
        <Adaptador_de_red>NAT</Adaptador_de_red>
    </ID>    
    <ID>
         <Nombre>Debian12</Nombre>
         <CPU>2</CPU>
         <RAM tamaño="MB">2048</RAM>
         <Nom.Disco>/home/user/VirtualBox VMs/Debian12/Debian12.vmdk</Nom.Disco>
         <Disco tamaño="GB">30</Disco> 
         <Adaptador_de_red>NAT</Adaptador_de_red>
    </ID>
    <ID>
         <Nombre>Windows7</Nombre>
         <CPU>1</CPU>
         <RAM tamaño="MB">2048</RAM>
         <Nom.Disco>/home/user/VirtualBox VMs/Windows7/Windows7.vdi</Nom.Disco>
         <Disco tamaño="GB">60</Disco> 
         <Adaptador_de_red>Adaptador puente</Adaptador_de_red>
    </ID>
</Máquinas_Virtuales>
